CREATE TYPE "SalesDispatchStatus" AS ENUM ('DRAFT', 'POSTED', 'DELIVERED', 'CANCELLED');
CREATE TABLE "sales_dispatch" ("id" TEXT NOT NULL, "number" TEXT NOT NULL, "salesOrderId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "dispatchAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "sourceWarehouseId" TEXT NOT NULL, "deliveryAddress" TEXT NOT NULL, "routeName" TEXT, "salespersonName" TEXT, "vehicleNumber" TEXT, "driverName" TEXT, "driverPhone" TEXT, "transporter" TEXT, "gatePassReference" TEXT, "notes" TEXT, "status" "SalesDispatchStatus" NOT NULL DEFAULT 'DRAFT', "createdByUserId" TEXT NOT NULL, "postedByUserId" TEXT, "postedAt" TIMESTAMP(3), "deliveredByUserId" TEXT, "deliveredAt" TIMESTAMP(3), "receiverName" TEXT, "deliveryNotes" TEXT, "cancelledByUserId" TEXT, "cancelledAt" TIMESTAMP(3), "cancellationReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "sales_dispatch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "sales_dispatch_line" ("id" TEXT NOT NULL, "salesDispatchId" TEXT NOT NULL, "salesOrderLineId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "cartons" INTEGER NOT NULL, "loosePieces" INTEGER NOT NULL, "totalPieces" DECIMAL(24,6) NOT NULL, "notes" TEXT, CONSTRAINT "sales_dispatch_line_pkey" PRIMARY KEY ("id"), CONSTRAINT "sales_dispatch_line_quantity" CHECK ("cartons" >= 0 AND "loosePieces" >= 0 AND "totalPieces" > 0));
CREATE TABLE "sales_dispatch_lot_allocation" ("id" TEXT NOT NULL, "salesDispatchLineId" TEXT NOT NULL, "productionLotId" TEXT NOT NULL, "quantity" DECIMAL(24,6) NOT NULL, CONSTRAINT "sales_dispatch_lot_allocation_pkey" PRIMARY KEY ("id"), CONSTRAINT "sales_dispatch_lot_allocation_quantity" CHECK ("quantity" > 0));
CREATE TABLE "sales_dispatch_sequence" ("year" INTEGER NOT NULL, "nextValue" INTEGER NOT NULL, CONSTRAINT "sales_dispatch_sequence_pkey" PRIMARY KEY ("year"));
ALTER TABLE "inventory_movement" ADD COLUMN "salesDispatchId" TEXT;
ALTER TABLE "inventory_movement" ADD COLUMN "salesDispatchLineId" TEXT;
ALTER TABLE "inventory_movement" ADD COLUMN "salesDispatchAllocationId" TEXT;
CREATE UNIQUE INDEX "sales_dispatch_number_key" ON "sales_dispatch"("number");
CREATE INDEX "sales_dispatch_salesOrderId_dispatchAt_idx" ON "sales_dispatch"("salesOrderId", "dispatchAt");
CREATE INDEX "sales_dispatch_customerId_dispatchAt_idx" ON "sales_dispatch"("customerId", "dispatchAt");
CREATE INDEX "sales_dispatch_status_dispatchAt_idx" ON "sales_dispatch"("status", "dispatchAt");
CREATE UNIQUE INDEX "sales_dispatch_line_salesDispatchId_salesOrderLineId_key" ON "sales_dispatch_line"("salesDispatchId", "salesOrderLineId");
CREATE UNIQUE INDEX "sales_dispatch_lot_allocation_salesDispatchLineId_productionLotId_key" ON "sales_dispatch_lot_allocation"("salesDispatchLineId", "productionLotId");
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_salesOrderId_fkey" FOREIGN KEY ("salesOrderId") REFERENCES "sales_order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_sourceWarehouseId_fkey" FOREIGN KEY ("sourceWarehouseId") REFERENCES "warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_postedByUserId_fkey" FOREIGN KEY ("postedByUserId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_deliveredByUserId_fkey" FOREIGN KEY ("deliveredByUserId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch" ADD CONSTRAINT "sales_dispatch_cancelledByUserId_fkey" FOREIGN KEY ("cancelledByUserId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch_line" ADD CONSTRAINT "sales_dispatch_line_salesDispatchId_fkey" FOREIGN KEY ("salesDispatchId") REFERENCES "sales_dispatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch_line" ADD CONSTRAINT "sales_dispatch_line_salesOrderLineId_fkey" FOREIGN KEY ("salesOrderLineId") REFERENCES "sales_order_line"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch_line" ADD CONSTRAINT "sales_dispatch_line_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch_lot_allocation" ADD CONSTRAINT "sales_dispatch_lot_allocation_salesDispatchLineId_fkey" FOREIGN KEY ("salesDispatchLineId") REFERENCES "sales_dispatch_line"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sales_dispatch_lot_allocation" ADD CONSTRAINT "sales_dispatch_lot_allocation_productionLotId_fkey" FOREIGN KEY ("productionLotId") REFERENCES "production_lot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "inventory_movement" ADD CONSTRAINT "inventory_movement_salesDispatchId_fkey" FOREIGN KEY ("salesDispatchId") REFERENCES "sales_dispatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "inventory_movement" ADD CONSTRAINT "inventory_movement_salesDispatchLineId_fkey" FOREIGN KEY ("salesDispatchLineId") REFERENCES "sales_dispatch_line"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "inventory_movement" ADD CONSTRAINT "inventory_movement_salesDispatchAllocationId_fkey" FOREIGN KEY ("salesDispatchAllocationId") REFERENCES "sales_dispatch_lot_allocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
